# Generated by Django 4.1.3 on 2023-11-10 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('telpon', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='min 8 digit', regex='^\\+?1?\\d{9,15}$')])),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('harga', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='movie/images/')),
                ('stok', models.IntegerField()),
                ('tersedia', models.CharField(choices=[('1', 'Tersedia'), ('0', 'Tidak tersedia')], max_length=1)),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.toko')),
            ],
        ),
    ]
