# Generated by Django 4.1.3 on 2023-11-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Keterangan',
            new_name='keterangan',
        ),
    ]
